#include "include/Const.h"
#include "../libs/json.hpp"

#include <iostream>
#include <fstream>

/* necessary for config work */

std::string CONFIG_FILE_NAME = "assets/config/cfg.json";
std::string FAILED_TO_OPEN_CONFIG_FILE_ERR = "Failed to open config file";

/* other */

std::string WELCOME_MESSAGE;

/* operator names */

std::string ADDITION_CONCATENATION_OPERATOR_NAME;
std::string SUBTRACTION_OPERATOR_NAME;
std::string MULTIPLICATION_OPERATOR_NAME;
std::string DIVISION_OPERATOR_NAME;
std::string SIN_OPERATOR_NAME;
std::string COS_OPERATOR_NAME;
std::string LOG10_OPERATOR_NAME;
std::string LN_OPERATOR_NAME;
std::string LOG2_OPERATOR_NAME;
std::string AVG_OPERATOR_NAME;
std::string REPETITION_OPERATOR_NAME;
std::string PADL_OPERATOR_NAME;
std::string PADR_OPERATOR_NAME;

/* error messages */

std::string NEGATIVE_ARGUMENT_ERR;
std::string ZERO_ARGUMENT_ERR;
std::string OVERFLOW_ERR;
std::string INVALID_ARITY_ERR;

/* command names */

std::string HELP_COMMAND_NAME;
std::string OPLIST_COMMAND_NAME;
std::string MAXSIZE_COMMAND_NAME;
std::string CURRSIZE_COMMAND_NAME;
std::string CREATE_COMMAND_NAME;
std::string IMPORT_COMMAND_NAME;
std::string ASSIGN_COMMAND_NAME;
std::string FORMULA_COMMAND_NAME;
std::string PRINT_COMMAND_NAME;
std::string EXPORT_COMMAND_NAME;
std::string EXIT_COMMAND_NAME;

/* command descriptions */

std::string HELP_COMMAND_DESCRIPTION;
std::string OPLIST_COMMAND_DESCRIPTION;
std::string MAXSIZE_COMMAND_DESCRIPTION;
std::string CURRSIZE_COMMAND_DESCRIPTION;
std::string CREATE_COMMAND_DESCRIPTION;
std::string IMPORT_COMMAND_DESCRIPTION;
std::string ASSIGN_COMMAND_DESCRIPTION;
std::string FORMULA_COMMAND_DESCRIPTION;
std::string PRINT_COMMAND_DESCRIPTION;
std::string EXPORT_COMMAND_DESCRIPTION;
std::string EXIT_COMMAND_DESCRIPTION;

/* notes */

std::string CELL_INDEX_NOTE;
std::string FILE_NAME_NOTE;
std::string CELL_RANGE_NOTE;

/* command output */

std::string HELP_COMMAND_OUTPUT;
std::string OPLIST_COMMAND_OUTPUT;
std::string MAXSIZE_COMMAND_OUTPUT;
std::string CURRSIZE_COMMAND_OUTPUT;
std::string CREATE_COMMAND_OUTPUT;
std::string IMPORT_COMMAND_OUTPUT;
std::string ASSIGN_COMMAND_OUTPUT;
std::string FORMULA_COMMAND_OUTPUT;
std::string PRINT_COMMAND_OUTPUT;
std::string EXPORT_COMMAND_OUTPUT;
std::string EXIT_COMMAND_OUTPUT;

/* constant names */

std::string PI_CONSTANT_NAME;
std::string E_CONSTANT_NAME;
std::string USERNAME_CONSTANT_NAME;

/* constant values */

std::string PI_CONSTANT_VALUE;
std::string E_CONSTANT_VALUE;
std::string USERNAME_CONSTANT_VALUE;

size_t NUMBER_OR_COLUMNS_MAX;
size_t NUMBER_OR_ROWS_MAX;
size_t SCREEN_WIDTH;

void loadConfig(nlohmann::json &config)
{
    // open config file
    std::ifstream configFile(CONFIG_FILE_NAME);
    if (!configFile.is_open())
        throw std::runtime_error(FAILED_TO_OPEN_CONFIG_FILE_ERR);

    // load content of config file
    configFile >> config;
}

void initializeConstValues()
{
    // load config file
    nlohmann::json config;
    loadConfig(config);

    WELCOME_MESSAGE = config["WELCOME_MESSAGE"];
    ADDITION_CONCATENATION_OPERATOR_NAME = config["ADDITION_CONCATENATION_OPERATOR_NAME"];
    SUBTRACTION_OPERATOR_NAME = config["SUBTRACTION_OPERATOR_NAME"];
    MULTIPLICATION_OPERATOR_NAME = config["MULTIPLICATION_OPERATOR_NAME"];
    DIVISION_OPERATOR_NAME = config["DIVISION_OPERATOR_NAME"];
    SIN_OPERATOR_NAME = config["SIN_OPERATOR_NAME"];
    COS_OPERATOR_NAME = config["COS_OPERATOR_NAME"];
    LOG10_OPERATOR_NAME = config["LOG10_OPERATOR_NAME"];
    LN_OPERATOR_NAME = config["LN_OPERATOR_NAME"];
    LOG2_OPERATOR_NAME = config["LOG2_OPERATOR_NAME"];
    AVG_OPERATOR_NAME = config["AVG_OPERATOR_NAME"];
    REPETITION_OPERATOR_NAME = config["REPETITION_OPERATOR_NAME"];
    PADL_OPERATOR_NAME = config["PADL_OPERATOR_NAME"];
    PADR_OPERATOR_NAME = config["PADR_OPERATOR_NAME"];
    NEGATIVE_ARGUMENT_ERR = config["NEGATIVE_ARGUMENT_ERR"];
    ZERO_ARGUMENT_ERR = config["ZERO_ARGUMENT_ERR"];
    OVERFLOW_ERR = config["OVERFLOW_ERR"];
    INVALID_ARITY_ERR = config["INVALID_ARITY_ERR"];
    HELP_COMMAND_NAME = config["HELP_COMMAND_NAME"];
    OPLIST_COMMAND_NAME = config["OPLIST_COMMAND_NAME"];
    MAXSIZE_COMMAND_NAME = config["MAXSIZE_COMMAND_NAME"];
    CURRSIZE_COMMAND_NAME = config["CURRSIZE_COMMAND_NAME"];
    CREATE_COMMAND_NAME = config["CREATE_COMMAND_NAME"];
    IMPORT_COMMAND_NAME = config["IMPORT_COMMAND_NAME"];
    ASSIGN_COMMAND_NAME = config["ASSIGN_COMMAND_NAME"];
    FORMULA_COMMAND_NAME = config["FORMULA_COMMAND_NAME"];
    PRINT_COMMAND_NAME = config["PRINT_COMMAND_NAME"];
    EXPORT_COMMAND_NAME = config["EXPORT_COMMAND_NAME"];
    EXIT_COMMAND_NAME = config["EXIT_COMMAND_NAME"];
    HELP_COMMAND_DESCRIPTION = config["HELP_COMMAND_DESCRIPTION"];
    OPLIST_COMMAND_DESCRIPTION = config["OPLIST_COMMAND_DESCRIPTION"];
    MAXSIZE_COMMAND_DESCRIPTION = config["MAXSIZE_COMMAND_DESCRIPTION"];
    CURRSIZE_COMMAND_DESCRIPTION = config["CURRSIZE_COMMAND_DESCRIPTION"];
    CREATE_COMMAND_DESCRIPTION = config["CREATE_COMMAND_DESCRIPTION"];
    IMPORT_COMMAND_DESCRIPTION = config["IMPORT_COMMAND_DESCRIPTION"];
    ASSIGN_COMMAND_DESCRIPTION = config["ASSIGN_COMMAND_DESCRIPTION"];
    FORMULA_COMMAND_DESCRIPTION = config["FORMULA_COMMAND_DESCRIPTION"];
    PRINT_COMMAND_DESCRIPTION = config["PRINT_COMMAND_DESCRIPTION"];
    EXPORT_COMMAND_DESCRIPTION = config["EXPORT_COMMAND_DESCRIPTION"];
    EXIT_COMMAND_DESCRIPTION = config["EXIT_COMMAND_DESCRIPTION"];
    CELL_INDEX_NOTE = config["CELL_INDEX_NOTE"];
    FILE_NAME_NOTE = config["FILE_NAME_NOTE"];
    CELL_RANGE_NOTE = config["CELL_RANGE_NOTE"];
    HELP_COMMAND_OUTPUT = config["HELP_COMMAND_OUTPUT"];
    OPLIST_COMMAND_OUTPUT = config["OPLIST_COMMAND_OUTPUT"];
    MAXSIZE_COMMAND_OUTPUT = config["MAXSIZE_COMMAND_OUTPUT"];
    CURRSIZE_COMMAND_OUTPUT = config["CURRSIZE_COMMAND_OUTPUT"];
    CREATE_COMMAND_OUTPUT = config["CREATE_COMMAND_OUTPUT"];
    IMPORT_COMMAND_OUTPUT = config["IMPORT_COMMAND_OUTPUT"];
    ASSIGN_COMMAND_OUTPUT = config["ASSIGN_COMMAND_OUTPUT"];
    FORMULA_COMMAND_OUTPUT = config["FORMULA_COMMAND_OUTPUT"];
    PRINT_COMMAND_OUTPUT = config["PRINT_COMMAND_OUTPUT"];
    EXPORT_COMMAND_OUTPUT = config["EXPORT_COMMAND_OUTPUT"];
    EXIT_COMMAND_OUTPUT = config["EXIT_COMMAND_OUTPUT"];
    PI_CONSTANT_NAME = config["PI_CONSTANT_NAME"];
    E_CONSTANT_NAME = config["E_CONSTANT_NAME"];
    USERNAME_CONSTANT_NAME = config["USERNAME_CONSTANT_NAME"];
    PI_CONSTANT_VALUE = config["PI_CONSTANT_VALUE"];
    E_CONSTANT_VALUE = config["E_CONSTANT_VALUE"];
    USERNAME_CONSTANT_VALUE = config["USERNAME_CONSTANT_VALUE"];
    NUMBER_OR_COLUMNS_MAX = config["NUMBER_OR_COLUMNS_MAX"];
    NUMBER_OR_ROWS_MAX = config["NUMBER_OR_ROWS_MAX"];
    SCREEN_WIDTH = config["SCREEN_WIDTH"];
}